<<<<<<< HEAD
app = "gantter"
primary_region = "iad"
=======
# fly.toml app configuration file generated for gantter on 2026-09-04T17:28:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gantter'
primary_region = 'ams'
>>>>>>> 0e47013260cb9804fda73de7f686fc126928f135

[build]
  dockerfile = 'Dockerfile'

[env]
<<<<<<< HEAD
  APP_BASE_URL = "https://gantter.fly.dev"
  DATABASE_PATH = "/data/data.sqlite"
  GOOGLE_REDIRECT_URI = "https://gantter.fly.dev/api/auth/google/callback"
  PORT = "8080"
  VITE_APP_MODE = "server"
=======
  APP_BASE_URL = 'https://gantter.fly.dev'
  DATABASE_PATH = '/data/data.sqlite'
  GOOGLE_REDIRECT_URI = 'https://gantter.fly.dev/api/auth/google/callback'
  PORT = '8080'
  VITE_APP_MODE = 'server'

[[mounts]]
  source = 'gantter_data'
  destination = '/data'
>>>>>>> 0e47013260cb9804fda73de7f686fc126928f135

[http_service]
  internal_port = 8080
  force_https = true
<<<<<<< HEAD
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  # Health Check correcto dentro del servicio HTTP
  [[http_service.checks]]
    grace_period = "10s"
    interval = "15s"
    method = "GET"
    path = "/api/health"
    timeout = "2s"

[[mounts]]
  source = "gantter_data"
  destination = "/data"
=======
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[metrics]]
  port = 8080
  path = '/api/health'
>>>>>>> 0e47013260cb9804fda73de7f686fc126928f135
